[versions]
ktor = "3.0.3"
kotlin = "2.1.0"
logback = "1.5.15"

[libraries]
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
